title_optimizer_task:
  description: >
    Analise e otimize este Título a seguir:{titulo}. Com base nas melhores práticas de SEO para ecommerce. 
    Certifique-se de incluir palavras-chave relevantes, respeitar o tamanho ideal dos títulos (50-60 caracteres).
  expected_output: >
    Uma lista com os seguintes elementos para cada título analisado:
    - Título atual do produto.
    - Sugestão de título otimizado.
    - Indicação de palavras-chave para configurar o SEO da página de produtos.
  agent: title_optimizer